/*
==============================================================================
 Parameter Name : pMinDelayMs
 SOAR Stage    : SOAR 1 – API Throttling Control
 Type          : Number
 Required      : Yes
 Purpose       : Define the minimum delay (in milliseconds) enforced
                 between successive MXToolbox API
*/                 
1100 meta [IsParameterQuery=true, Type="Number", IsParameterQueryRequired=true]